@BASE_URL=http://localhost:3000/app/v1

GET {{BASE_URL}}
# Content-Type: application/json

###
GET {{BASE_URL}}/todos


###
GET {{BASE_URL}}/todo/692ab368566d22a4a6760b90

###

POST {{BASE_URL}}/add-todo
Content-Type: application/json

{
    "title":"do home work",
    "priority":"Low",
    "due":"",
    "status":"completed"
}

###
PUT {{BASE_URL}}/update/692a8b6a580e8662ff4df6ff
Content-Type: application/json

{
    "title":"Update Todo",
    "priority":"High",
    "due":"",
    "status":"pending"
}

###

DELETE {{BASE_URL}}/delete/692a8ba690f818df475d995d

###

DELETE {{BASE_URL}}/delete-all