@BASE_URL=http://localhost:3000/app/v1
@AuthorizationToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthbmhhaXlhQDEyMyIsInVzZXJfaWQiOiI2OTM1NGI1OWRlZjdhNmE3ZDU0NWVjNWQiLCJpYXQiOjE3NjUxMTE3NzYsImV4cCI6MTc2NTExMjY3Nn0.ZFnVgyJNPFZ4L5OXFmsy5M9-kijWdd0CUcUiYdS1HvU

GET {{BASE_URL}}
# Content-Type: application/json

###
GET {{BASE_URL}}/todos
Authorization: Bearer {{AuthorizationToken}}


###
GET {{BASE_URL}}/todo/692ab368566d22a4a6760b90
Authorization: Bearer {{AuthorizationToken}}

###

POST {{BASE_URL}}/add-todo
Authorization: Bearer {{AuthorizationToken}}
Content-Type: application/json

{
    "title":"do zumba",
    "priority":"Low",
    "due":"",
    "status":"completed"
}

###
PUT {{BASE_URL}}/update/692ab369566d22a4a6760b92
Authorization: Bearer {{AuthorizationToken}}
Content-Type: application/json

{
    "title":"Update Todo",
    "priority":"High",
    "due":"",
    "status":"pending"
}

###

DELETE {{BASE_URL}}/delete/692ab368566d22a4a6760b90
Authorization: Bearer {{AuthorizationToken}}

###

DELETE {{BASE_URL}}/delete-all
Authorization: Bearer {{AuthorizationToken}}