@BASE_URL=http://localhost:3000/app/v1

GET {{BASE_URL}}
# Content-Type: application/json

###
GET {{BASE_URL}}/todos


###
GET {{BASE_URL}}/todo/692a702f1769a4fb7d6e9030

###

PUT {{BASE_URL}}/add-todo
Content-Type: application/json

{
    "title":"do home work",
    "priority":"Low",
    "due":"",
    "status":"completed"
}